// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Deal is the predicate function for deal builders.
type Deal func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
