services:
  postgres:
    image: postgres:18-alpine
    environment:
      PGDATA: /var/lib/postgresql/18/docker
      POSTGRES_DB: game_deals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_18_data:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/game_deals
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: celery -A game_deals worker -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/game_deals
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery-beat:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: celery -A game_deals beat -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/game_deals
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

volumes:
  postgres_18_data: {}
