# Generated by Django 5.2.10 on 2026-01-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
