# Generated by Django 5.2.9 on 2025-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Game title', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (null if free)', max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='Is the game free?')),
                ('expires', models.DateTimeField(help_text='Deal expiration date')),
                ('image', models.URLField(help_text='Game image URL', max_length=500)),
                ('link', models.URLField(help_text='Store URL to purchase', max_length=500)),
                ('notifications_sent', models.JSONField(blank=True, default=dict, help_text='Track notification status per channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='deals_deal_created_483300_idx'), models.Index(fields=['expires'], name='deals_deal_expires_3d03d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('auth', models.CharField(help_text='Auth key for push', max_length=255)),
                ('p256dh', models.CharField(help_text='P256dh key for push', max_length=255)),
                ('channel', models.CharField(db_index=True, default='main', help_text='Notification channel (main, test, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', '-created_at'], name='deals_pushs_channel_6bfc0c_idx')],
            },
        ),
    ]
