# Generated by Django 5.2.9 on 2025-12-30 01:00

import deals.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Game title', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Deal status', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (auto-generated)', max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Discounted price (0 for free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expires', models.DateTimeField(blank=True, help_text='Deal expiration date (required when published)', null=True)),
                ('image', models.URLField(blank=True, help_text='Game image URL (required when published)', max_length=500, null=True)),
                ('palette_colors', models.JSONField(blank=True, default=deals.models.default_palette, help_text='6-color palette extracted from image (array of hex strings)')),
                ('foreground_color', models.CharField(blank=True, default='#ffffff', help_text='Foreground text color for contrast (from palette or black/white)', max_length=7)),
                ('link', models.URLField(blank=True, help_text='Store URL to purchase (required when published)', max_length=500, null=True)),
                ('notifications_sent', models.JSONField(blank=True, default=dict, help_text='Track notification status per channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='deals_deal_created_483300_idx'), models.Index(fields=['expires'], name='deals_deal_expires_3d03d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('auth', models.CharField(help_text='Auth key for push', max_length=255)),
                ('p256dh', models.CharField(help_text='P256dh key for push', max_length=255)),
                ('channel', models.CharField(db_index=True, default='main', help_text='Notification channel (main, test, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', '-created_at'], name='deals_pushs_channel_6bfc0c_idx')],
            },
        ),
    ]
