# Generated by Django 5.2.10 on 2026-01-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_flower', 'Can view Flower monitoring dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
