apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../app

patches:
- path: patches/deployment.yaml

nameSuffix: -celery

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    component: celery
