// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/WWPOL/Game-Deals/backend/ent/deal"
	"github.com/WWPOL/Game-Deals/backend/ent/image"
	"github.com/WWPOL/Game-Deals/backend/ent/predicate"
	"github.com/WWPOL/Game-Deals/backend/ent/user"
)

// DealUpdate is the builder for updating Deal entities.
type DealUpdate struct {
	config
	hooks    []Hook
	mutation *DealMutation
}

// Where appends a list predicates to the DealUpdate builder.
func (du *DealUpdate) Where(ps ...predicate.Deal) *DealUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DealUpdate) SetName(s string) *DealUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DealUpdate) SetNillableName(s *string) *DealUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetExpiresAt sets the "expires_at" field.
func (du *DealUpdate) SetExpiresAt(t time.Time) *DealUpdate {
	du.mutation.SetExpiresAt(t)
	return du
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (du *DealUpdate) SetNillableExpiresAt(t *time.Time) *DealUpdate {
	if t != nil {
		du.SetExpiresAt(*t)
	}
	return du
}

// SetPrice sets the "price" field.
func (du *DealUpdate) SetPrice(f float64) *DealUpdate {
	du.mutation.ResetPrice()
	du.mutation.SetPrice(f)
	return du
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (du *DealUpdate) SetNillablePrice(f *float64) *DealUpdate {
	if f != nil {
		du.SetPrice(*f)
	}
	return du
}

// AddPrice adds f to the "price" field.
func (du *DealUpdate) AddPrice(f float64) *DealUpdate {
	du.mutation.AddPrice(f)
	return du
}

// SetLink sets the "link" field.
func (du *DealUpdate) SetLink(s string) *DealUpdate {
	du.mutation.SetLink(s)
	return du
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (du *DealUpdate) SetNillableLink(s *string) *DealUpdate {
	if s != nil {
		du.SetLink(*s)
	}
	return du
}

// AddImageIDs adds the "image" edge to the Image entity by IDs.
func (du *DealUpdate) AddImageIDs(ids ...int) *DealUpdate {
	du.mutation.AddImageIDs(ids...)
	return du
}

// AddImage adds the "image" edges to the Image entity.
func (du *DealUpdate) AddImage(i ...*Image) *DealUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return du.AddImageIDs(ids...)
}

// AddCreatedByIDs adds the "created_by" edge to the User entity by IDs.
func (du *DealUpdate) AddCreatedByIDs(ids ...int) *DealUpdate {
	du.mutation.AddCreatedByIDs(ids...)
	return du
}

// AddCreatedBy adds the "created_by" edges to the User entity.
func (du *DealUpdate) AddCreatedBy(u ...*User) *DealUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.AddCreatedByIDs(ids...)
}

// Mutation returns the DealMutation object of the builder.
func (du *DealUpdate) Mutation() *DealMutation {
	return du.mutation
}

// ClearImage clears all "image" edges to the Image entity.
func (du *DealUpdate) ClearImage() *DealUpdate {
	du.mutation.ClearImage()
	return du
}

// RemoveImageIDs removes the "image" edge to Image entities by IDs.
func (du *DealUpdate) RemoveImageIDs(ids ...int) *DealUpdate {
	du.mutation.RemoveImageIDs(ids...)
	return du
}

// RemoveImage removes "image" edges to Image entities.
func (du *DealUpdate) RemoveImage(i ...*Image) *DealUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return du.RemoveImageIDs(ids...)
}

// ClearCreatedBy clears all "created_by" edges to the User entity.
func (du *DealUpdate) ClearCreatedBy() *DealUpdate {
	du.mutation.ClearCreatedBy()
	return du
}

// RemoveCreatedByIDs removes the "created_by" edge to User entities by IDs.
func (du *DealUpdate) RemoveCreatedByIDs(ids ...int) *DealUpdate {
	du.mutation.RemoveCreatedByIDs(ids...)
	return du
}

// RemoveCreatedBy removes "created_by" edges to User entities.
func (du *DealUpdate) RemoveCreatedBy(u ...*User) *DealUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.RemoveCreatedByIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DealUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DealUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DealUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DealUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DealUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deal.Table, deal.Columns, sqlgraph.NewFieldSpec(deal.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(deal.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.ExpiresAt(); ok {
		_spec.SetField(deal.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.Price(); ok {
		_spec.SetField(deal.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.AddedPrice(); ok {
		_spec.AddField(deal.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.Link(); ok {
		_spec.SetField(deal.FieldLink, field.TypeString, value)
	}
	if du.mutation.ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedImageIDs(); len(nodes) > 0 && !du.mutation.ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedCreatedByIDs(); len(nodes) > 0 && !du.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DealUpdateOne is the builder for updating a single Deal entity.
type DealUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DealMutation
}

// SetName sets the "name" field.
func (duo *DealUpdateOne) SetName(s string) *DealUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DealUpdateOne) SetNillableName(s *string) *DealUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetExpiresAt sets the "expires_at" field.
func (duo *DealUpdateOne) SetExpiresAt(t time.Time) *DealUpdateOne {
	duo.mutation.SetExpiresAt(t)
	return duo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (duo *DealUpdateOne) SetNillableExpiresAt(t *time.Time) *DealUpdateOne {
	if t != nil {
		duo.SetExpiresAt(*t)
	}
	return duo
}

// SetPrice sets the "price" field.
func (duo *DealUpdateOne) SetPrice(f float64) *DealUpdateOne {
	duo.mutation.ResetPrice()
	duo.mutation.SetPrice(f)
	return duo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (duo *DealUpdateOne) SetNillablePrice(f *float64) *DealUpdateOne {
	if f != nil {
		duo.SetPrice(*f)
	}
	return duo
}

// AddPrice adds f to the "price" field.
func (duo *DealUpdateOne) AddPrice(f float64) *DealUpdateOne {
	duo.mutation.AddPrice(f)
	return duo
}

// SetLink sets the "link" field.
func (duo *DealUpdateOne) SetLink(s string) *DealUpdateOne {
	duo.mutation.SetLink(s)
	return duo
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (duo *DealUpdateOne) SetNillableLink(s *string) *DealUpdateOne {
	if s != nil {
		duo.SetLink(*s)
	}
	return duo
}

// AddImageIDs adds the "image" edge to the Image entity by IDs.
func (duo *DealUpdateOne) AddImageIDs(ids ...int) *DealUpdateOne {
	duo.mutation.AddImageIDs(ids...)
	return duo
}

// AddImage adds the "image" edges to the Image entity.
func (duo *DealUpdateOne) AddImage(i ...*Image) *DealUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return duo.AddImageIDs(ids...)
}

// AddCreatedByIDs adds the "created_by" edge to the User entity by IDs.
func (duo *DealUpdateOne) AddCreatedByIDs(ids ...int) *DealUpdateOne {
	duo.mutation.AddCreatedByIDs(ids...)
	return duo
}

// AddCreatedBy adds the "created_by" edges to the User entity.
func (duo *DealUpdateOne) AddCreatedBy(u ...*User) *DealUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.AddCreatedByIDs(ids...)
}

// Mutation returns the DealMutation object of the builder.
func (duo *DealUpdateOne) Mutation() *DealMutation {
	return duo.mutation
}

// ClearImage clears all "image" edges to the Image entity.
func (duo *DealUpdateOne) ClearImage() *DealUpdateOne {
	duo.mutation.ClearImage()
	return duo
}

// RemoveImageIDs removes the "image" edge to Image entities by IDs.
func (duo *DealUpdateOne) RemoveImageIDs(ids ...int) *DealUpdateOne {
	duo.mutation.RemoveImageIDs(ids...)
	return duo
}

// RemoveImage removes "image" edges to Image entities.
func (duo *DealUpdateOne) RemoveImage(i ...*Image) *DealUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return duo.RemoveImageIDs(ids...)
}

// ClearCreatedBy clears all "created_by" edges to the User entity.
func (duo *DealUpdateOne) ClearCreatedBy() *DealUpdateOne {
	duo.mutation.ClearCreatedBy()
	return duo
}

// RemoveCreatedByIDs removes the "created_by" edge to User entities by IDs.
func (duo *DealUpdateOne) RemoveCreatedByIDs(ids ...int) *DealUpdateOne {
	duo.mutation.RemoveCreatedByIDs(ids...)
	return duo
}

// RemoveCreatedBy removes "created_by" edges to User entities.
func (duo *DealUpdateOne) RemoveCreatedBy(u ...*User) *DealUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.RemoveCreatedByIDs(ids...)
}

// Where appends a list predicates to the DealUpdate builder.
func (duo *DealUpdateOne) Where(ps ...predicate.Deal) *DealUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DealUpdateOne) Select(field string, fields ...string) *DealUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Deal entity.
func (duo *DealUpdateOne) Save(ctx context.Context) (*Deal, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DealUpdateOne) SaveX(ctx context.Context) *Deal {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DealUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DealUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DealUpdateOne) sqlSave(ctx context.Context) (_node *Deal, err error) {
	_spec := sqlgraph.NewUpdateSpec(deal.Table, deal.Columns, sqlgraph.NewFieldSpec(deal.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deal.FieldID)
		for _, f := range fields {
			if !deal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(deal.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.ExpiresAt(); ok {
		_spec.SetField(deal.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.Price(); ok {
		_spec.SetField(deal.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.AddedPrice(); ok {
		_spec.AddField(deal.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.Link(); ok {
		_spec.SetField(deal.FieldLink, field.TypeString, value)
	}
	if duo.mutation.ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedImageIDs(); len(nodes) > 0 && !duo.mutation.ImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.ImageTable,
			Columns: []string{deal.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedCreatedByIDs(); len(nodes) > 0 && !duo.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deal.CreatedByTable,
			Columns: []string{deal.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deal{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
