// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DealsColumns holds the columns for the "deals" table.
	DealsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "link", Type: field.TypeString},
	}
	// DealsTable holds the schema information for the "deals" table.
	DealsTable = &schema.Table{
		Name:       "deals",
		Columns:    DealsColumns,
		PrimaryKey: []*schema.Column{DealsColumns[0]},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deal_image", Type: field.TypeInt, Nullable: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_deals_image",
				Columns:    []*schema.Column{ImagesColumns[1]},
				RefColumns: []*schema.Column{DealsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "deal_created_by", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_deals_created_by",
				Columns:    []*schema.Column{UsersColumns[2]},
				RefColumns: []*schema.Column{DealsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DealsTable,
		ImagesTable,
		UsersTable,
	}
)

func init() {
	ImagesTable.ForeignKeys[0].RefTable = DealsTable
	UsersTable.ForeignKeys[0].RefTable = DealsTable
}
