"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Site URL for building absolute URLs (e.g., in Discord embeds)
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme (must be before django.contrib.admin)
    'django_object_actions',  # Django Object Actions for custom admin actions
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tz_detect',  # Timezone detection
    'django_extensions',
    'django_select2',  # Select2 widgets for autocomplete
    'django_celery_results',  # Celery result backend using Django ORM
    'rest_framework',  # Django REST Framework for API endpoints

    # Local apps
    'common',
    'deals',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection (after SessionMiddleware)
    'tz_detect.middleware.TimezoneMiddleware',  # Timezone detection (after SessionMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.middleware.CurrentUserMiddleware',  # Store current user in thread-local storage
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates override app templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/game_deals',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Limit available languages (add more as needed)
LANGUAGES = [
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage Configuration
# Use S3-compatible storage for production, local filesystem for development
USE_S3 = os.environ.get('USE_S3_STORAGE', 'false').lower() == 'true'

if USE_S3:
    # S3-compatible storage (AWS S3, Digital Ocean Spaces, MinIO, etc.)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.environ.get('S3_ACCESS_KEY'),
                "secret_key": os.environ.get('S3_SECRET_KEY'),
                "bucket_name": os.environ.get('S3_BUCKET_NAME'),
                "region_name": os.environ.get('S3_REGION'),
                "endpoint_url": os.environ.get('S3_ENDPOINT_URL'),  # Required for non-AWS providers
                "custom_domain": os.environ.get('S3_CUSTOM_DOMAIN'),  # Optional CDN domain
                "object_parameters": {
                    "CacheControl": "max-age=86400",  # 1 day cache
                },
                "file_overwrite": False,  # Don't overwrite existing files
                "default_acl": "public-read",  # Make uploaded files publicly readable
            }
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # Override MEDIA_URL to point to S3-compatible storage
    if os.environ.get('S3_CUSTOM_DOMAIN'):
        MEDIA_URL = f"https://{os.environ.get('S3_CUSTOM_DOMAIN')}/"
    elif os.environ.get('S3_ENDPOINT_URL'):
        # For custom endpoints (DO Spaces, MinIO, etc.)
        MEDIA_URL = f"{os.environ.get('S3_ENDPOINT_URL')}/{os.environ.get('S3_BUCKET_NAME')}/"
    else:
        # AWS S3 default
        bucket = os.environ.get('S3_BUCKET_NAME')
        region = os.environ.get('S3_REGION')
        MEDIA_URL = f"https://{bucket}.s3.{region}.amazonaws.com/"
else:
    # Local filesystem storage (development)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Temporary directory for image downloads (used by color extraction)
# In production, this should be ephemeral storage (emptyDir in Kubernetes)
TEMP_DOWNLOAD_DIR = os.environ.get('TEMP_DOWNLOAD_DIR', '/tmp/game-deals')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # Use Django ORM for task results
CELERY_CACHE_BACKEND = 'django-cache'  # Use Django cache for caching results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_RESULT_EXTENDED = True  # Store additional task metadata

# Google Custom Search API Configuration
# Get your API key from: https://console.cloud.google.com/apis/credentials
# Create a Custom Search Engine at: https://programmablesearchengine.google.com/
GOOGLE_API_KEY = os.environ['GOOGLE_API_KEY']
GOOGLE_SEARCH_ENGINE_ID = os.environ['GOOGLE_SEARCH_ENGINE_ID']

# Admin Branding
UNFOLD = {
    "SITE_TITLE": "Game Deals Admin",
    "SITE_HEADER": "Game Deals",
    "SITE_SYMBOL": "🎮",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": True,  # Enable language selector in admin
}
