// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	"github.com/go-faster/jx"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDeal implements createDeal operation.
//
// Creates a new Deal and persists it to storage.
//
// POST /deals
func (UnimplementedHandler) CreateDeal(ctx context.Context, req *CreateDealReq) (r CreateDealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateImage implements createImage operation.
//
// Creates a new Image and persists it to storage.
//
// POST /images
func (UnimplementedHandler) CreateImage(ctx context.Context, req jx.Raw) (r CreateImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Creates a new User and persists it to storage.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserReq) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDeal implements deleteDeal operation.
//
// Deletes the Deal with the requested ID.
//
// DELETE /deals/{id}
func (UnimplementedHandler) DeleteDeal(ctx context.Context, params DeleteDealParams) (r DeleteDealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteImage implements deleteImage operation.
//
// Deletes the Image with the requested ID.
//
// DELETE /images/{id}
func (UnimplementedHandler) DeleteImage(ctx context.Context, params DeleteImageParams) (r DeleteImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Deletes the User with the requested ID.
//
// DELETE /users/{id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeal implements listDeal operation.
//
// List Deals.
//
// GET /deals
func (UnimplementedHandler) ListDeal(ctx context.Context, params ListDealParams) (r ListDealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDealCreatedBy implements listDealCreatedBy operation.
//
// List attached CreatedBys.
//
// GET /deals/{id}/created-by
func (UnimplementedHandler) ListDealCreatedBy(ctx context.Context, params ListDealCreatedByParams) (r ListDealCreatedByRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDealImage implements listDealImage operation.
//
// List attached Images.
//
// GET /deals/{id}/image
func (UnimplementedHandler) ListDealImage(ctx context.Context, params ListDealImageParams) (r ListDealImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListImage implements listImage operation.
//
// List Images.
//
// GET /images
func (UnimplementedHandler) ListImage(ctx context.Context, params ListImageParams) (r ListImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUser implements listUser operation.
//
// List Users.
//
// GET /users
func (UnimplementedHandler) ListUser(ctx context.Context, params ListUserParams) (r ListUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadDeal implements readDeal operation.
//
// Finds the Deal with the requested ID and returns it.
//
// GET /deals/{id}
func (UnimplementedHandler) ReadDeal(ctx context.Context, params ReadDealParams) (r ReadDealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadImage implements readImage operation.
//
// Finds the Image with the requested ID and returns it.
//
// GET /images/{id}
func (UnimplementedHandler) ReadImage(ctx context.Context, params ReadImageParams) (r ReadImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadUser implements readUser operation.
//
// Finds the User with the requested ID and returns it.
//
// GET /users/{id}
func (UnimplementedHandler) ReadUser(ctx context.Context, params ReadUserParams) (r ReadUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDeal implements updateDeal operation.
//
// Updates a Deal and persists changes to storage.
//
// PATCH /deals/{id}
func (UnimplementedHandler) UpdateDeal(ctx context.Context, req *UpdateDealReq, params UpdateDealParams) (r UpdateDealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateImage implements updateImage operation.
//
// Updates a Image and persists changes to storage.
//
// PATCH /images/{id}
func (UnimplementedHandler) UpdateImage(ctx context.Context, req jx.Raw, params UpdateImageParams) (r UpdateImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// Updates a User and persists changes to storage.
//
// PATCH /users/{id}
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
