// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	"github.com/go-faster/jx"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateDeal implements createDeal operation.
	//
	// Creates a new Deal and persists it to storage.
	//
	// POST /deals
	CreateDeal(ctx context.Context, req *CreateDealReq) (CreateDealRes, error)
	// CreateImage implements createImage operation.
	//
	// Creates a new Image and persists it to storage.
	//
	// POST /images
	CreateImage(ctx context.Context, req jx.Raw) (CreateImageRes, error)
	// CreateUser implements createUser operation.
	//
	// Creates a new User and persists it to storage.
	//
	// POST /users
	CreateUser(ctx context.Context, req *CreateUserReq) (CreateUserRes, error)
	// DeleteDeal implements deleteDeal operation.
	//
	// Deletes the Deal with the requested ID.
	//
	// DELETE /deals/{id}
	DeleteDeal(ctx context.Context, params DeleteDealParams) (DeleteDealRes, error)
	// DeleteImage implements deleteImage operation.
	//
	// Deletes the Image with the requested ID.
	//
	// DELETE /images/{id}
	DeleteImage(ctx context.Context, params DeleteImageParams) (DeleteImageRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Deletes the User with the requested ID.
	//
	// DELETE /users/{id}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// ListDeal implements listDeal operation.
	//
	// List Deals.
	//
	// GET /deals
	ListDeal(ctx context.Context, params ListDealParams) (ListDealRes, error)
	// ListDealCreatedBy implements listDealCreatedBy operation.
	//
	// List attached CreatedBys.
	//
	// GET /deals/{id}/created-by
	ListDealCreatedBy(ctx context.Context, params ListDealCreatedByParams) (ListDealCreatedByRes, error)
	// ListDealImage implements listDealImage operation.
	//
	// List attached Images.
	//
	// GET /deals/{id}/image
	ListDealImage(ctx context.Context, params ListDealImageParams) (ListDealImageRes, error)
	// ListImage implements listImage operation.
	//
	// List Images.
	//
	// GET /images
	ListImage(ctx context.Context, params ListImageParams) (ListImageRes, error)
	// ListUser implements listUser operation.
	//
	// List Users.
	//
	// GET /users
	ListUser(ctx context.Context, params ListUserParams) (ListUserRes, error)
	// ReadDeal implements readDeal operation.
	//
	// Finds the Deal with the requested ID and returns it.
	//
	// GET /deals/{id}
	ReadDeal(ctx context.Context, params ReadDealParams) (ReadDealRes, error)
	// ReadImage implements readImage operation.
	//
	// Finds the Image with the requested ID and returns it.
	//
	// GET /images/{id}
	ReadImage(ctx context.Context, params ReadImageParams) (ReadImageRes, error)
	// ReadUser implements readUser operation.
	//
	// Finds the User with the requested ID and returns it.
	//
	// GET /users/{id}
	ReadUser(ctx context.Context, params ReadUserParams) (ReadUserRes, error)
	// UpdateDeal implements updateDeal operation.
	//
	// Updates a Deal and persists changes to storage.
	//
	// PATCH /deals/{id}
	UpdateDeal(ctx context.Context, req *UpdateDealReq, params UpdateDealParams) (UpdateDealRes, error)
	// UpdateImage implements updateImage operation.
	//
	// Updates a Image and persists changes to storage.
	//
	// PATCH /images/{id}
	UpdateImage(ctx context.Context, req jx.Raw, params UpdateImageParams) (UpdateImageRes, error)
	// UpdateUser implements updateUser operation.
	//
	// Updates a User and persists changes to storage.
	//
	// PATCH /users/{id}
	UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (UpdateUserRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
