// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"time"

	"github.com/go-faster/jx"
)

type CreateDealReq struct {
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
	Price     float64   `json:"price"`
	Link      string    `json:"link"`
	Image     []int     `json:"image"`
	CreatedBy []int     `json:"created_by"`
}

// GetName returns the value of Name.
func (s *CreateDealReq) GetName() string {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *CreateDealReq) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *CreateDealReq) GetPrice() float64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *CreateDealReq) GetLink() string {
	return s.Link
}

// GetImage returns the value of Image.
func (s *CreateDealReq) GetImage() []int {
	return s.Image
}

// GetCreatedBy returns the value of CreatedBy.
func (s *CreateDealReq) GetCreatedBy() []int {
	return s.CreatedBy
}

// SetName sets the value of Name.
func (s *CreateDealReq) SetName(val string) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *CreateDealReq) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *CreateDealReq) SetPrice(val float64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *CreateDealReq) SetLink(val string) {
	s.Link = val
}

// SetImage sets the value of Image.
func (s *CreateDealReq) SetImage(val []int) {
	s.Image = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *CreateDealReq) SetCreatedBy(val []int) {
	s.CreatedBy = val
}

type CreateUserReq struct {
	Username string `json:"username"`
}

// GetUsername returns the value of Username.
func (s *CreateUserReq) GetUsername() string {
	return s.Username
}

// SetUsername sets the value of Username.
func (s *CreateUserReq) SetUsername(val string) {
	s.Username = val
}

// Ref: #/components/schemas/DealCreate
type DealCreate struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
	Price     float64   `json:"price"`
	Link      string    `json:"link"`
}

// GetID returns the value of ID.
func (s *DealCreate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *DealCreate) GetName() string {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *DealCreate) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *DealCreate) GetPrice() float64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *DealCreate) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *DealCreate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DealCreate) SetName(val string) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *DealCreate) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *DealCreate) SetPrice(val float64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *DealCreate) SetLink(val string) {
	s.Link = val
}

func (*DealCreate) createDealRes() {}

// Ref: #/components/schemas/Deal_CreatedByList
type DealCreatedByList struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *DealCreatedByList) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *DealCreatedByList) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *DealCreatedByList) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *DealCreatedByList) SetUsername(val string) {
	s.Username = val
}

// Ref: #/components/schemas/Deal_ImageList
type DealImageList struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *DealImageList) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *DealImageList) SetID(val int) {
	s.ID = val
}

// Ref: #/components/schemas/DealList
type DealList struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
	Price     float64   `json:"price"`
	Link      string    `json:"link"`
}

// GetID returns the value of ID.
func (s *DealList) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *DealList) GetName() string {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *DealList) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *DealList) GetPrice() float64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *DealList) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *DealList) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DealList) SetName(val string) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *DealList) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *DealList) SetPrice(val float64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *DealList) SetLink(val string) {
	s.Link = val
}

// Ref: #/components/schemas/DealRead
type DealRead struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
	Price     float64   `json:"price"`
	Link      string    `json:"link"`
}

// GetID returns the value of ID.
func (s *DealRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *DealRead) GetName() string {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *DealRead) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *DealRead) GetPrice() float64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *DealRead) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *DealRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DealRead) SetName(val string) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *DealRead) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *DealRead) SetPrice(val float64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *DealRead) SetLink(val string) {
	s.Link = val
}

func (*DealRead) readDealRes() {}

// Ref: #/components/schemas/DealUpdate
type DealUpdate struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
	Price     float64   `json:"price"`
	Link      string    `json:"link"`
}

// GetID returns the value of ID.
func (s *DealUpdate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *DealUpdate) GetName() string {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *DealUpdate) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *DealUpdate) GetPrice() float64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *DealUpdate) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *DealUpdate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DealUpdate) SetName(val string) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *DealUpdate) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *DealUpdate) SetPrice(val float64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *DealUpdate) SetLink(val string) {
	s.Link = val
}

func (*DealUpdate) updateDealRes() {}

// DeleteDealNoContent is response for DeleteDeal operation.
type DeleteDealNoContent struct{}

func (*DeleteDealNoContent) deleteDealRes() {}

// DeleteImageNoContent is response for DeleteImage operation.
type DeleteImageNoContent struct{}

func (*DeleteImageNoContent) deleteImageRes() {}

// DeleteUserNoContent is response for DeleteUser operation.
type DeleteUserNoContent struct{}

func (*DeleteUserNoContent) deleteUserRes() {}

// Ref: #/components/schemas/ImageCreate
type ImageCreate struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *ImageCreate) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *ImageCreate) SetID(val int) {
	s.ID = val
}

func (*ImageCreate) createImageRes() {}

// Ref: #/components/schemas/ImageList
type ImageList struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *ImageList) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *ImageList) SetID(val int) {
	s.ID = val
}

// Ref: #/components/schemas/ImageRead
type ImageRead struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *ImageRead) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *ImageRead) SetID(val int) {
	s.ID = val
}

func (*ImageRead) readImageRes() {}

// Ref: #/components/schemas/ImageUpdate
type ImageUpdate struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *ImageUpdate) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *ImageUpdate) SetID(val int) {
	s.ID = val
}

func (*ImageUpdate) updateImageRes() {}

type ListDealCreatedByOKApplicationJSON []DealCreatedByList

func (*ListDealCreatedByOKApplicationJSON) listDealCreatedByRes() {}

type ListDealImageOKApplicationJSON []DealImageList

func (*ListDealImageOKApplicationJSON) listDealImageRes() {}

type ListDealOKApplicationJSON []DealList

func (*ListDealOKApplicationJSON) listDealRes() {}

type ListImageOKApplicationJSON []ImageList

func (*ListImageOKApplicationJSON) listImageRes() {}

type ListUserOKApplicationJSON []UserList

func (*ListUserOKApplicationJSON) listUserRes() {}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type R400 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R400) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R400) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R400) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R400) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R400) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R400) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R400) createDealRes()        {}
func (*R400) createImageRes()       {}
func (*R400) createUserRes()        {}
func (*R400) deleteDealRes()        {}
func (*R400) deleteImageRes()       {}
func (*R400) deleteUserRes()        {}
func (*R400) listDealCreatedByRes() {}
func (*R400) listDealImageRes()     {}
func (*R400) listDealRes()          {}
func (*R400) listImageRes()         {}
func (*R400) listUserRes()          {}
func (*R400) readDealRes()          {}
func (*R400) readImageRes()         {}
func (*R400) readUserRes()          {}
func (*R400) updateDealRes()        {}
func (*R400) updateImageRes()       {}
func (*R400) updateUserRes()        {}

type R404 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R404) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R404) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R404) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R404) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R404) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R404) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R404) deleteDealRes()        {}
func (*R404) deleteImageRes()       {}
func (*R404) deleteUserRes()        {}
func (*R404) listDealCreatedByRes() {}
func (*R404) listDealImageRes()     {}
func (*R404) listDealRes()          {}
func (*R404) listImageRes()         {}
func (*R404) listUserRes()          {}
func (*R404) readDealRes()          {}
func (*R404) readImageRes()         {}
func (*R404) readUserRes()          {}
func (*R404) updateDealRes()        {}
func (*R404) updateImageRes()       {}
func (*R404) updateUserRes()        {}

type R409 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R409) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R409) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R409) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R409) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R409) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R409) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R409) createDealRes()        {}
func (*R409) createImageRes()       {}
func (*R409) createUserRes()        {}
func (*R409) deleteDealRes()        {}
func (*R409) deleteImageRes()       {}
func (*R409) deleteUserRes()        {}
func (*R409) listDealCreatedByRes() {}
func (*R409) listDealImageRes()     {}
func (*R409) listDealRes()          {}
func (*R409) listImageRes()         {}
func (*R409) listUserRes()          {}
func (*R409) readDealRes()          {}
func (*R409) readImageRes()         {}
func (*R409) readUserRes()          {}
func (*R409) updateDealRes()        {}
func (*R409) updateImageRes()       {}
func (*R409) updateUserRes()        {}

type R500 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R500) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R500) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R500) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R500) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R500) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R500) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R500) createDealRes()        {}
func (*R500) createImageRes()       {}
func (*R500) createUserRes()        {}
func (*R500) deleteDealRes()        {}
func (*R500) deleteImageRes()       {}
func (*R500) deleteUserRes()        {}
func (*R500) listDealCreatedByRes() {}
func (*R500) listDealImageRes()     {}
func (*R500) listDealRes()          {}
func (*R500) listImageRes()         {}
func (*R500) listUserRes()          {}
func (*R500) readDealRes()          {}
func (*R500) readImageRes()         {}
func (*R500) readUserRes()          {}
func (*R500) updateDealRes()        {}
func (*R500) updateImageRes()       {}
func (*R500) updateUserRes()        {}

type UpdateDealReq struct {
	Name      OptString   `json:"name"`
	ExpiresAt OptDateTime `json:"expires_at"`
	Price     OptFloat64  `json:"price"`
	Link      OptString   `json:"link"`
	Image     []int       `json:"image"`
	CreatedBy []int       `json:"created_by"`
}

// GetName returns the value of Name.
func (s *UpdateDealReq) GetName() OptString {
	return s.Name
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *UpdateDealReq) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetPrice returns the value of Price.
func (s *UpdateDealReq) GetPrice() OptFloat64 {
	return s.Price
}

// GetLink returns the value of Link.
func (s *UpdateDealReq) GetLink() OptString {
	return s.Link
}

// GetImage returns the value of Image.
func (s *UpdateDealReq) GetImage() []int {
	return s.Image
}

// GetCreatedBy returns the value of CreatedBy.
func (s *UpdateDealReq) GetCreatedBy() []int {
	return s.CreatedBy
}

// SetName sets the value of Name.
func (s *UpdateDealReq) SetName(val OptString) {
	s.Name = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *UpdateDealReq) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetPrice sets the value of Price.
func (s *UpdateDealReq) SetPrice(val OptFloat64) {
	s.Price = val
}

// SetLink sets the value of Link.
func (s *UpdateDealReq) SetLink(val OptString) {
	s.Link = val
}

// SetImage sets the value of Image.
func (s *UpdateDealReq) SetImage(val []int) {
	s.Image = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *UpdateDealReq) SetCreatedBy(val []int) {
	s.CreatedBy = val
}

type UpdateUserReq struct {
	Username OptString `json:"username"`
}

// GetUsername returns the value of Username.
func (s *UpdateUserReq) GetUsername() OptString {
	return s.Username
}

// SetUsername sets the value of Username.
func (s *UpdateUserReq) SetUsername(val OptString) {
	s.Username = val
}

// Ref: #/components/schemas/UserCreate
type UserCreate struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *UserCreate) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *UserCreate) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *UserCreate) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *UserCreate) SetUsername(val string) {
	s.Username = val
}

func (*UserCreate) createUserRes() {}

// Ref: #/components/schemas/UserList
type UserList struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *UserList) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *UserList) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *UserList) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *UserList) SetUsername(val string) {
	s.Username = val
}

// Ref: #/components/schemas/UserRead
type UserRead struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *UserRead) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *UserRead) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *UserRead) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *UserRead) SetUsername(val string) {
	s.Username = val
}

func (*UserRead) readUserRes() {}

// Ref: #/components/schemas/UserUpdate
type UserUpdate struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *UserUpdate) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *UserUpdate) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *UserUpdate) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *UserUpdate) SetUsername(val string) {
	s.Username = val
}

func (*UserUpdate) updateUserRes() {}
