// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateDealRes interface {
	createDealRes()
}

type CreateImageRes interface {
	createImageRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteDealRes interface {
	deleteDealRes()
}

type DeleteImageRes interface {
	deleteImageRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListDealCreatedByRes interface {
	listDealCreatedByRes()
}

type ListDealImageRes interface {
	listDealImageRes()
}

type ListDealRes interface {
	listDealRes()
}

type ListImageRes interface {
	listImageRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadDealRes interface {
	readDealRes()
}

type ReadImageRes interface {
	readImageRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateDealRes interface {
	updateDealRes()
}

type UpdateImageRes interface {
	updateImageRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
