// Code generated by ent, DO NOT EDIT.

package ogent

import "github.com/WWPOL/Game-Deals/backend/ent"

func NewDealCreate(e *ent.Deal) *DealCreate {
	if e == nil {
		return nil
	}
	var ret DealCreate
	ret.ID = e.ID
	ret.Name = e.Name
	ret.ExpiresAt = e.ExpiresAt
	ret.Price = e.Price
	ret.Link = e.Link
	return &ret
}

func NewDealCreates(es []*ent.Deal) []DealCreate {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealCreate, len(es))
	for i, e := range es {
		r[i] = NewDealCreate(e).Elem()
	}
	return r
}

func (d *DealCreate) Elem() DealCreate {
	if d == nil {
		return DealCreate{}
	}
	return *d
}

func NewDealList(e *ent.Deal) *DealList {
	if e == nil {
		return nil
	}
	var ret DealList
	ret.ID = e.ID
	ret.Name = e.Name
	ret.ExpiresAt = e.ExpiresAt
	ret.Price = e.Price
	ret.Link = e.Link
	return &ret
}

func NewDealLists(es []*ent.Deal) []DealList {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealList, len(es))
	for i, e := range es {
		r[i] = NewDealList(e).Elem()
	}
	return r
}

func (d *DealList) Elem() DealList {
	if d == nil {
		return DealList{}
	}
	return *d
}

func NewDealRead(e *ent.Deal) *DealRead {
	if e == nil {
		return nil
	}
	var ret DealRead
	ret.ID = e.ID
	ret.Name = e.Name
	ret.ExpiresAt = e.ExpiresAt
	ret.Price = e.Price
	ret.Link = e.Link
	return &ret
}

func NewDealReads(es []*ent.Deal) []DealRead {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealRead, len(es))
	for i, e := range es {
		r[i] = NewDealRead(e).Elem()
	}
	return r
}

func (d *DealRead) Elem() DealRead {
	if d == nil {
		return DealRead{}
	}
	return *d
}

func NewDealUpdate(e *ent.Deal) *DealUpdate {
	if e == nil {
		return nil
	}
	var ret DealUpdate
	ret.ID = e.ID
	ret.Name = e.Name
	ret.ExpiresAt = e.ExpiresAt
	ret.Price = e.Price
	ret.Link = e.Link
	return &ret
}

func NewDealUpdates(es []*ent.Deal) []DealUpdate {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealUpdate, len(es))
	for i, e := range es {
		r[i] = NewDealUpdate(e).Elem()
	}
	return r
}

func (d *DealUpdate) Elem() DealUpdate {
	if d == nil {
		return DealUpdate{}
	}
	return *d
}

func NewDealCreatedByList(e *ent.User) *DealCreatedByList {
	if e == nil {
		return nil
	}
	var ret DealCreatedByList
	ret.ID = e.ID
	ret.Username = e.Username
	return &ret
}

func NewDealCreatedByLists(es []*ent.User) []DealCreatedByList {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealCreatedByList, len(es))
	for i, e := range es {
		r[i] = NewDealCreatedByList(e).Elem()
	}
	return r
}

func (u *DealCreatedByList) Elem() DealCreatedByList {
	if u == nil {
		return DealCreatedByList{}
	}
	return *u
}

func NewDealImageList(e *ent.Image) *DealImageList {
	if e == nil {
		return nil
	}
	var ret DealImageList
	ret.ID = e.ID
	return &ret
}

func NewDealImageLists(es []*ent.Image) []DealImageList {
	if len(es) == 0 {
		return nil
	}
	r := make([]DealImageList, len(es))
	for i, e := range es {
		r[i] = NewDealImageList(e).Elem()
	}
	return r
}

func (i *DealImageList) Elem() DealImageList {
	if i == nil {
		return DealImageList{}
	}
	return *i
}

func NewImageCreate(e *ent.Image) *ImageCreate {
	if e == nil {
		return nil
	}
	var ret ImageCreate
	ret.ID = e.ID
	return &ret
}

func NewImageCreates(es []*ent.Image) []ImageCreate {
	if len(es) == 0 {
		return nil
	}
	r := make([]ImageCreate, len(es))
	for i, e := range es {
		r[i] = NewImageCreate(e).Elem()
	}
	return r
}

func (i *ImageCreate) Elem() ImageCreate {
	if i == nil {
		return ImageCreate{}
	}
	return *i
}

func NewImageList(e *ent.Image) *ImageList {
	if e == nil {
		return nil
	}
	var ret ImageList
	ret.ID = e.ID
	return &ret
}

func NewImageLists(es []*ent.Image) []ImageList {
	if len(es) == 0 {
		return nil
	}
	r := make([]ImageList, len(es))
	for i, e := range es {
		r[i] = NewImageList(e).Elem()
	}
	return r
}

func (i *ImageList) Elem() ImageList {
	if i == nil {
		return ImageList{}
	}
	return *i
}

func NewImageRead(e *ent.Image) *ImageRead {
	if e == nil {
		return nil
	}
	var ret ImageRead
	ret.ID = e.ID
	return &ret
}

func NewImageReads(es []*ent.Image) []ImageRead {
	if len(es) == 0 {
		return nil
	}
	r := make([]ImageRead, len(es))
	for i, e := range es {
		r[i] = NewImageRead(e).Elem()
	}
	return r
}

func (i *ImageRead) Elem() ImageRead {
	if i == nil {
		return ImageRead{}
	}
	return *i
}

func NewImageUpdate(e *ent.Image) *ImageUpdate {
	if e == nil {
		return nil
	}
	var ret ImageUpdate
	ret.ID = e.ID
	return &ret
}

func NewImageUpdates(es []*ent.Image) []ImageUpdate {
	if len(es) == 0 {
		return nil
	}
	r := make([]ImageUpdate, len(es))
	for i, e := range es {
		r[i] = NewImageUpdate(e).Elem()
	}
	return r
}

func (i *ImageUpdate) Elem() ImageUpdate {
	if i == nil {
		return ImageUpdate{}
	}
	return *i
}

func NewUserCreate(e *ent.User) *UserCreate {
	if e == nil {
		return nil
	}
	var ret UserCreate
	ret.ID = e.ID
	ret.Username = e.Username
	return &ret
}

func NewUserCreates(es []*ent.User) []UserCreate {
	if len(es) == 0 {
		return nil
	}
	r := make([]UserCreate, len(es))
	for i, e := range es {
		r[i] = NewUserCreate(e).Elem()
	}
	return r
}

func (u *UserCreate) Elem() UserCreate {
	if u == nil {
		return UserCreate{}
	}
	return *u
}

func NewUserList(e *ent.User) *UserList {
	if e == nil {
		return nil
	}
	var ret UserList
	ret.ID = e.ID
	ret.Username = e.Username
	return &ret
}

func NewUserLists(es []*ent.User) []UserList {
	if len(es) == 0 {
		return nil
	}
	r := make([]UserList, len(es))
	for i, e := range es {
		r[i] = NewUserList(e).Elem()
	}
	return r
}

func (u *UserList) Elem() UserList {
	if u == nil {
		return UserList{}
	}
	return *u
}

func NewUserRead(e *ent.User) *UserRead {
	if e == nil {
		return nil
	}
	var ret UserRead
	ret.ID = e.ID
	ret.Username = e.Username
	return &ret
}

func NewUserReads(es []*ent.User) []UserRead {
	if len(es) == 0 {
		return nil
	}
	r := make([]UserRead, len(es))
	for i, e := range es {
		r[i] = NewUserRead(e).Elem()
	}
	return r
}

func (u *UserRead) Elem() UserRead {
	if u == nil {
		return UserRead{}
	}
	return *u
}

func NewUserUpdate(e *ent.User) *UserUpdate {
	if e == nil {
		return nil
	}
	var ret UserUpdate
	ret.ID = e.ID
	ret.Username = e.Username
	return &ret
}

func NewUserUpdates(es []*ent.User) []UserUpdate {
	if len(es) == 0 {
		return nil
	}
	r := make([]UserUpdate, len(es))
	for i, e := range es {
		r[i] = NewUserUpdate(e).Elem()
	}
	return r
}

func (u *UserUpdate) Elem() UserUpdate {
	if u == nil {
		return UserUpdate{}
	}
	return *u
}
