#!/usr/bin/env bash
if [ -z "$CONTAINER_CLI" ]; then
  CONTAINER_CLI=podman
fi

prog_dir=$(realpath $(dirname "$0"))

sudo podman run \
	   -it \
	   --rm \
	   -p 8001:8001 \
	   --net host \
	   -v "$prog_dir/dev-proxy.conf:/etc/nginx/nginx.conf:ro" \
     -v "$prog_dir:/mnt" \
	   nginx:latest
